# Generated by Django 5.1.1 on 2024-09-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='faculty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
