# Generated by Django 5.1 on 2024-08-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0002_subject_remove_event_attendees_and_more"),
    ]

    operations = []
