# Generated by Django 5.1 on 2024-08-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0003_auto_20240830_0454"),
    ]

    operations = []
