# Generated by Django 5.1 on 2024-08-30 05:10

from django.db import migrations

def create_default_subjects(apps, schema_editor):
    Subject = apps.get_model('calendar_events', 'Subject')
    subjects = [
        "Principles of Operating Systems",
        "Information Security",
        "Essentials of Management",
        "Software Project Management",
        "Software Engineering",
        "Principles of Operating Systems Laboratory",
        "Information Security Laboratory",
        "Creativity, Problem Solving & Innovation"
    ]
    for subject_name in subjects:
        Subject.objects.get_or_create(name=subject_name)

class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0004_auto_20240830_0456'),
    ]

    operations = [
        migrations.RunPython(create_default_subjects),
    ]