# Generated by Django 5.1 on 2024-08-30 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_events", "0004_auto_20240830_0456"),
        ("calendar_events", "0005_auto_20240830_0510"),
    ]

    operations = []
