# Generated by Django 5.1.1 on 2024-09-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0006_merge_0004_auto_20240830_0456_0005_auto_20240830_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('MID_EXAM', 'Mid-Semester Exam'), ('MID_LAB_EXAM', 'Mid-Semester Laboratory Exam'), ('LAB_SUBMISSION', 'Laboratory Submission & Viva-Voce'), ('END_EXAM', 'End Semester Exam')], max_length=20),
        ),
    ]
