# Generated by Django 5.1.1 on 2024-09-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0009_remove_event_all_day_event_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Lab Record Submission', 'Lab Record Submission'), ('Viva Voce & Record Submission', 'Viva Voce & Record Submission'), ('Lab midsem exam', 'Lab midsem exam'), ('Midsem Exam', 'Midsem Exam'), ('Quiz', 'Quiz'), ('Assignment', 'Assignment'), ('Test', 'Test')], default='Assignment', max_length=50),
        ),
    ]
