# Generated by Django 5.0.2 on 2024-08-21 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
